### PR TITLE
Popover menu

### PR DESCRIPTION
**Pull request by LazeMSS**
Changed the drop down menu into a popover menu to improve the look and feel.
Added a fallback error if no wifi is detected
Added an option to use Font Awesome as wifi status indicator

### CODE REVIEW

**Comment by ManuelMcLure** [comment]
At least in my install of OctoPrint, I much prefer the look and feel of the dropdown list:

- I don't have to do anything in Themeify to get it to match the look and feel of the rest of the UI. With the popover if I am using the Discorded theme the text ends up being gray on a white background unless I add custom CSS to Themeify.
- I don't like word-wrapping IPV6 addresses.
- The FontAwesome icon does not understand the Themeify theme either, so you end up with dark grey and darker grey.
- I noticed that you hard-coded the top and bottom padding on the icon instead of using JavaScript to calculate them. That causes the navbar to change height  (very noticeable if you add the PSU Control plugin - when you hover over the PSU Control plugin icon the highlight is taller than the highlights of the other icons on the navbar). That's why I added the Javascript code to calculate the padding for the WiFi icon.

I appreciate the idea, and if those issues can be resolved I'll reexamine merging this in. But as of now I prefer the current behavior. Part of my philosophy for this is "it just works" so anything that requires the user to do extra work (like adding custom entries into Themeify) is a non-starter.

**Comment by LazeMSS** [comment]
I will look into these "bugs" :)

- Themify skinning is limited because its not a full bootstrap skin - users will experience the same problem with the dropdown if they have serial log etc. - its the way the official "plugins" shows extended information thats why I went with that solution.
- We can just expand the dropdown width - i just wanted to keep it simpel
- The font colors should understand that - I will test
- The top padding should follow the standard padding/margins of bootstrap but I will look again

**Comment by LazeMSS** [comment]
I have added a fix/repoort to themeify to support popover in the skins - its also "missing" for all the default popovers as mentioned earlier - like the serial log and undervoltage - popovers seem to the way extra info is shown by the official octoprint developers - thats why I went with that solution. I will update when it gets fixed.

**Comment by ManuelMcLure** [comment]
I implemented this differently, so I'll close this PR.

**Pull request closed without merging**
